### PR TITLE
Seeded DB with details for all 4 challenges

### PR DESCRIPTION
**Pull request by nanselmo**
might still need some editing but now we have 4 challenges that make sense

### CODE REVIEW

**Comment by nanselmo** [comment]
Also fixed mis-directed link when clicking for the next mission

**Comment by shaistaansari** [comment]
yaay!!!. We can test it out now.
ᐧ

On Wed, Nov 4, 2015 at 9:26 PM, Nicki Anselmo notifications@github.com
wrote:

> ## might still need some editing but now we have 4 challenges that make sense
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/schehackschi-team11/the-mission/pull/27
> Commit Summary
> - added text for Challenge 2
> - made 4 distinct challenges
> 
> File Changes
> - _M_ db/seeds.rb
>   https://github.com/schehackschi-team11/the-mission/pull/27/files#diff-0
>   (211)
> 
> Patch Links:
> - https://github.com/schehackschi-team11/the-mission/pull/27.patch
> - https://github.com/schehackschi-team11/the-mission/pull/27.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/schehackschi-team11/the-mission/pull/27.

## 

Shaista Ansari
@shaistaaansari
Web developer

**Comment by kieranklaassen** [comment]
Nice work! @nickianselmo

**Comment by shaistaansari** [comment]
Nicki, can you please send me your email so that I can include you in the
email that I am sending out to 8th Light?

On Fri, Nov 6, 2015 at 9:32 AM, Kieran Klaassen notifications@github.com
wrote:

> Nice work! @nickianselmo https://github.com/nickianselmo
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/schehackschi-team11/the-mission/pull/27#issuecomment-154423504
> .

## 

Shaista Ansari
@shaistaaansari
Web developer

**Comment by nanselmo** [comment]
nickianselmo@gmail.com

**Comment by nickianselmo** [comment]
Also, how does the new version get pushed to heroku now? I can push my
forked branch, but I think it makes sense if Keiran can enable Heroku to
access the main repo (
https://dashboard.heroku.com/apps/createher/deploy/github)

**Comment by shaistaansari** [comment]
Let me know if there is an issue with pushing to Heroku.

Shaista

On Fri, Nov 6, 2015 at 12:39 PM, nickianselmo notifications@github.com
wrote:

> Also, how does the new version get pushed to heroku now? I can push my
> forked branch, but I think it makes sense if Keiran can enable Heroku to
> access the main repo (
> https://dashboard.heroku.com/apps/createher/deploy/github)
> 
> On Fri, Nov 6, 2015 at 9:52 AM, Nicki Anselmo notifications@github.com
> wrote:
> 
> > nickianselmo@gmail.com
> > 
> > On Fri, Nov 6, 2015 at 9:47 AM, shaistaansari notifications@github.com
> > wrote:
> > 
> > > Nicki, can you please send me your email so that I can include you in
> > > the
> > > email that I am sending out to 8th Light?
> > > 
> > > On Fri, Nov 6, 2015 at 9:32 AM, Kieran Klaassen <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Nice work! @nickianselmo https://github.com/nickianselmo
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/schehackschi-team11/the-mission/pull/27#issuecomment-154423504
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Shaista Ansari
> > > @shaistaaansari
> > > Web developer
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/schehackschi-team11/the-mission/pull/27#issuecomment-154444026
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/schehackschi-team11/the-mission/pull/27#issuecomment-154446218
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/schehackschi-team11/the-mission/pull/27#issuecomment-154481685
> .

## 

Shaista Ansari
@shaistaaansari
Web developer

**Comment by kieranklaassen** [comment]
Let us set up Continuus integration for Heroku so that it automatically pushes when we update here yes

**Pull request merged**
